CREATE TABLE IF NOT EXISTS certificate_issue_registry (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    batch_id BIGINT UNSIGNED DEFAULT NULL,
    certificate_id BIGINT UNSIGNED DEFAULT NULL,
    student_id BIGINT UNSIGNED DEFAULT NULL,
    issue_identifier CHAR(64) NOT NULL,
    certificate_code VARCHAR(80) DEFAULT NULL,
    full_name_snapshot VARCHAR(180) NOT NULL,
    course_name VARCHAR(180) NOT NULL,
    completion_date DATE NOT NULL,
    workload_hours SMALLINT UNSIGNED NOT NULL,
    requested_by VARCHAR(180) NOT NULL,
    requested_ip VARCHAR(45) DEFAULT NULL,
    emission_status ENUM('generated', 'blocked', 'failed') NOT NULL DEFAULT 'generated',
    blocked_reason VARCHAR(255) DEFAULT NULL,
    payload_json JSON DEFAULT NULL,
    issued_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_certificate_issue_registry_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_certificate_issue_registry_batch FOREIGN KEY (batch_id) REFERENCES generation_batches(id) ON DELETE SET NULL,
    CONSTRAINT fk_certificate_issue_registry_certificate FOREIGN KEY (certificate_id) REFERENCES certificates(id) ON DELETE SET NULL,
    CONSTRAINT fk_certificate_issue_registry_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE SET NULL,
    KEY idx_certificate_issue_registry_lookup (company_id, issue_identifier, emission_status),
    KEY idx_certificate_issue_registry_batch (batch_id, emission_status),
    KEY idx_certificate_issue_registry_date (issued_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
